### PR TITLE
fix: Removing any logic that would write to checkout or to the session

### PR DESCRIPTION
**Pull request by rvitorper**
#### What problem is this solving?
Writing in the session causes a bug with profile

#### How should this be tested?
- The CI runs all the automated tests
- Smoke test: [Workspace](https://testecustomprices--b2bstore.myvtex.com)

#### Checklist/Reminders

- [x] Updated `README.md`.
- [x] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [x] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Type of changes

✔️ | Type of Change
---|---
✔️ | Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements

### CODE REVIEW

**Review by gsasouza — APPROVED** [review]
LGTM. but, just to be aware, why it's not persisted on session anymore?

**Comment by rvitorper** [comment]
As we write to the session on the server-side, we end up destroying information on the session - somehow, no idea how exactly. This behaviour would break every app that would depend on the profile information that exists in the session.

**Review by alessandrasa — CHANGES_REQUESTED** [review]
We need alignement to follow this approach

**Comment by rvitorper** [comment]
Needs further investigation

**Pull request closed without merging**
